### ISSUE TITLE
Structure Error - when use HTML tag (Bug?)

### ISSUE THREAD

**Issue by Milor123** [lesterchan/wp-postratings#112]
Hi @lesterchan , I am not sure how work it, but when I use tags for align. the plugin not work correctly.

**When I try add it with tags:**
**`<p style="text-align: right;">[ratings]</p>`**
![image](https://user-images.githubusercontent.com/14153649/32687238-26cfb866-c686-11e7-9e4b-bd7c3bb19ab6.png)
<br/>
**Without Tags:**
**`[ratings]`**
![image](https://user-images.githubusercontent.com/14153649/32687247-4d086f3c-c686-11e7-808c-4d61b1fe2258.png)

My problem of the this https://github.com/lesterchan/wp-postratings/issues/109 the which was closed, was being caused by the HTML tags

**Comment by lesterchan** [comment]
I am sorry, I can't help you. This is related to your styling and theme and is not within my support scope and has nothing to do with the plugin itself.

**Comment by lesterchan** [comment]
What are the two errors?

**Comment by Milor123** [comment]
The two erros are the same of https://github.com/lesterchan/wp-postratings/issues/109 and the error in the "Agreggeratings" only appear if the post have reviews and is within HTML tags

**Comment by lesterchan** [comment]
Probably something wrong with your theme HTML structure or some conflict with another plugin. I would recommend testing with the default theme and without any other plugins activated.

You should get only 1 errror, https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Flesterchan.net%2Fwordpress%2F2009%2F02%2F23%2Fwordpress-powerpoint-template%2F

Which can be fixed by ```add_filter( 'wp_postratings_site_logo', 'wp_postratings_site_logo' );
function wp_postratings_site_logo( $url ) {
return 'http://placehold.it/350/150.png';
}```` as stated in the FAQ.
